apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-deployment
  labels:
    app: note-app
  namespace: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
        - name: note-app
          image: altamsh/note-app:v20250604082941
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
