apiVersion: v1
kind: Service
metadata:
  name: note-app-service
  namespace: note-app
spec:
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
