name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    # Setting up environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pyhton
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install npm
      #Test the Code
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # For tag update after trigger
      - name: Docker tag
        id: version
        run: |
          version=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$version" >> $GITHUB_ENV

      #Push the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t altamsh/note-app:${{  env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push altamsh/note-app:${{  env.VERSION }}
