name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    # Setting up environment
    steps:
      - name: Checkout code
        uses: actions/checkout@2

      - name: Setup pyhton
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip Install flaske8
      #Test the Code
      - name: Run linting tests
        run: |
          fkaje8 --ignore=E501,F401 .

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # For tag update after trigger
      - name: Docker tag
        id: version
        run: |
          version=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      #Push the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t altamsh/note-app:latest:${{  env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push altamsh/note-app:latest:${{  env.VERSION }}
